[theme]
base="light"
primaryColor="#000000"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#FFFFFF"
textColor="#000000"
font="sans serif"

[ui]
# 🔒 Bloquea el cambio automático por parte del sistema
hideTopBar = false
